-- ══════════════════════════════════════════════════════════════════════════
-- 002_merge_audit_logs.sql — Merge duplicate audit tables
--
-- SCHEMA_REVIEW.md Issue #1: audit_log (singular) and audit_logs (plural)
-- record the same concept with divergent naming/types. This migration folds
-- audit_log into the canonical audit_logs and drops the singular table.
--
-- Column mapping (audit_log -> audit_logs):
--   tenant_id     -> org_id          (uuid; org_id is NOT NULL, see WHERE below)
--   actor_id      -> actor_user_id   (uuid)
--   entity_type   -> target_type     (text)
--   entity_id     -> target_id       (text -> uuid, GUARDED cast, see below)
--   diff          -> before_state / after_state
--                    (audit_log.diff is {"before":..,"after":..}, written by
--                     authz.AuditDiff; split into the two state columns)
--   created_at    -> created_at
--   (none)        -> ip_address      (NULL — audit_log never captured an IP)
--   id            -> (regenerated by audit_logs' IDENTITY; not carried over)
--
-- Guards:
--   * entity_id is free-form text; role.* actions store a UUID, but user.role.*
--     actions store a compound "userId/roleId" that is NOT a valid UUID. Only
--     UUID-shaped strings are cast into the uuid target_id; anything else keeps
--     target_id NULL and the original value is preserved as a jsonb note in
--     after_state ({"original_entity_id": "..."}) so no data is lost and the
--     cast never crashes the migration.
--   * org_id is NOT NULL. audit_log.tenant_id is nullable; rows with a NULL
--     tenant cannot map to a NOT NULL org and are skipped (WHERE tenant_id IS
--     NOT NULL). Such rows are orphaned audit entries with no owning org.
-- ══════════════════════════════════════════════════════════════════════════

-- Backfill audit_log rows into the canonical audit_logs table.
INSERT INTO public.audit_logs
    (org_id, actor_user_id, action, target_type, target_id, before_state, after_state, ip_address, created_at)
SELECT
    tenant_id,
    actor_id,
    action,
    entity_type,
    CASE
        WHEN entity_id ~ '^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$'
            THEN entity_id::uuid
        ELSE NULL
    END,
    diff -> 'before',
    CASE
        WHEN entity_id ~ '^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$'
            THEN diff -> 'after'
        ELSE COALESCE(diff -> 'after', '{}'::jsonb) || jsonb_build_object('original_entity_id', entity_id)
    END,
    NULL::inet,
    created_at
FROM public.audit_log
WHERE tenant_id IS NOT NULL;

-- Drop the redundant singular table. Cascades its own pkey, indexes, sequence,
-- and FK constraints; nothing else references audit_log.
DROP TABLE public.audit_log;
