#!/usr/bin/env bash
# ══════════════════════════════════════════════════════════════════════════════
# scripts/db-erd.sh — Generate an ER diagram from the live DB schema
# Introspects information_schema/pg_catalog directly — no table list is hardcoded.
# Outputs:
#   docs/erd.md   — Mermaid source, renders on GitHub
#   docs/erd.html — interactive viewer: zoom + export to SVG/PNG/.mmd
# ══════════════════════════════════════════════════════════════════════════════
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
CONTAINER="mindforge_postgres_dev"
MD_FILE="${PROJECT_ROOT}/docs/erd.md"
HTML_FILE="${PROJECT_ROOT}/docs/erd.html"

RED='\033[0;31m'
GREEN='\033[0;32m'
BLUE='\033[0;34m'
NC='\033[0m'

info()    { echo -e "${BLUE}[erd]${NC} $*"; }
success() { echo -e "${GREEN}[erd]${NC} $*"; }
error()   { echo -e "${RED}[erd]${NC} $*" >&2; exit 1; }

if [[ -f "${PROJECT_ROOT}/.env" ]]; then
  set -a
  # shellcheck disable=SC1091
  source "${PROJECT_ROOT}/.env"
  set +a
fi

POSTGRES_USER="${POSTGRES_USER:-mindforge}"
POSTGRES_DB="${POSTGRES_DB:-mindforge_dev}"

if ! docker inspect "$CONTAINER" &>/dev/null; then
  error "Container '$CONTAINER' is not running. Start it with: make dev-up"
fi

psql_exec() {
  docker exec "$CONTAINER" psql -U "$POSTGRES_USER" -d "$POSTGRES_DB" -v ON_ERROR_STOP=1 -t -A -F'|' -c "$1"
}

info "Reading columns..."
columns="$(psql_exec "
  SELECT table_name, column_name, data_type
  FROM information_schema.columns
  WHERE table_schema = 'public'
  ORDER BY table_name, ordinal_position;
")"

info "Reading primary keys..."
pks="$(psql_exec "
  SELECT tc.table_name, kcu.column_name
  FROM information_schema.table_constraints tc
  JOIN information_schema.key_column_usage kcu
    ON tc.constraint_name = kcu.constraint_name AND tc.table_schema = kcu.table_schema
  WHERE tc.constraint_type = 'PRIMARY KEY' AND tc.table_schema = 'public';
")"

info "Reading foreign keys..."
fks="$(psql_exec "
  SELECT tc.table_name, kcu.column_name, ccu.table_name, ccu.column_name
  FROM information_schema.table_constraints tc
  JOIN information_schema.key_column_usage kcu
    ON tc.constraint_name = kcu.constraint_name AND tc.table_schema = kcu.table_schema
  JOIN information_schema.constraint_column_usage ccu
    ON tc.constraint_name = ccu.constraint_name AND tc.table_schema = ccu.table_schema
  WHERE tc.constraint_type = 'FOREIGN KEY' AND tc.table_schema = 'public';
")"

table_count="$(cut -d'|' -f1 <<< "$columns" | sort -u | wc -l | tr -d ' ')"
info "Found ${table_count} tables. Building diagram..."

# ─── Build Mermaid erDiagram body once, reused by both outputs ──────────────
diagram_body="$(
  echo "erDiagram"

  cut -d'|' -f1 <<< "$columns" | sort -u | while IFS= read -r table; do
    [[ -z "$table" ]] && continue
    echo "    ${table} {"
    awk -F'|' -v t="$table" '$1 == t { print $2, $3 }' <<< "$columns" | while read -r col dtype; do
      is_pk="$(awk -F'|' -v t="$table" -v c="$col" '$1 == t && $2 == c { print "PK" }' <<< "$pks")"
      dtype_clean="$(tr ' ' '_' <<< "$dtype")"
      echo "        ${dtype_clean} ${col} ${is_pk}"
    done
    echo "    }"
  done

  awk -F'|' '{ print $1"|"$3"|"$2 }' <<< "$fks" | sort -u | while IFS='|' read -r child parent col; do
    [[ -z "$child" ]] && continue
    echo "    ${parent} ||--o{ ${child} : \"${col}\""
  done
)"

rel_count="$(grep -c '||--o{' <<< "$diagram_body" || true)"
generated_at="$(date -u +"%Y-%m-%d %H:%M UTC")"

# ─── docs/erd.md — plain Mermaid source, renders natively on GitHub ─────────
{
  echo "<!-- AUTO-GENERATED by scripts/db-erd.sh from the live schema — do not edit by hand. -->"
  echo "# Database ER Diagram"
  echo ""
  echo '```mermaid'
  echo "$diagram_body"
  echo '```'
} > "$MD_FILE"

# ─── docs/erd.html — interactive viewer with zoom + export ──────────────────
info "Rendering interactive viewer..."

cat > "$HTML_FILE" <<'HTML_PART_A'
<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>MindForge — Database ER Diagram</title>
<style>
  :root { color-scheme: light dark; }
  * { box-sizing: border-box; }
  body {
    margin: 0; font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Inter, sans-serif;
    background: #f6f7f9; color: #1a1d21;
  }
  @media (prefers-color-scheme: dark) {
    body { background: #16181d; color: #e6e8eb; }
  }
  header {
    padding: 20px 28px; background: linear-gradient(135deg, #4f46e5, #7c3aed);
    color: #fff; display: flex; align-items: baseline; gap: 14px; flex-wrap: wrap;
  }
  header h1 { font-size: 18px; margin: 0; font-weight: 600; }
  header .meta { font-size: 13px; opacity: 0.85; }
  .toolbar {
    position: sticky; top: 0; z-index: 10; display: flex; justify-content: space-between;
    gap: 12px; flex-wrap: wrap; padding: 10px 20px; background: #fff; border-bottom: 1px solid #e3e5e8;
  }
  @media (prefers-color-scheme: dark) {
    .toolbar { background: #1e2127; border-color: #2c3038; }
  }
  .group { display: flex; gap: 8px; }
  button {
    padding: 7px 14px; font-size: 13px; border-radius: 6px; border: 1px solid #d7d9dc;
    background: #fff; color: inherit; cursor: pointer;
  }
  button:hover { background: #f0f1f3; }
  @media (prefers-color-scheme: dark) {
    button { background: #262a31; border-color: #3a3f47; }
    button:hover { background: #2f333b; }
  }
  #diagram-wrap { overflow: auto; padding: 24px; height: calc(100vh - 116px); }
  #diagram { display: inline-block; background: #fff; border-radius: 10px; padding: 20px; box-shadow: 0 1px 3px rgba(0,0,0,0.12); }
  @media (prefers-color-scheme: dark) {
    #diagram { background: #1e2127; }
  }
</style>
</head>
<body>
<header>
  <h1>MindForge · Database ER Diagram</h1>
HTML_PART_A

printf '  <span class="meta">%s tables · %s relationships · generated %s</span>\n' \
  "$table_count" "$rel_count" "$generated_at" >> "$HTML_FILE"

cat >> "$HTML_FILE" <<'HTML_PART_B'
</header>
<div class="toolbar">
  <div class="group">
    <button id="zoomOut" title="Zoom out">−</button>
    <button id="zoomReset" title="Reset zoom">Reset</button>
    <button id="zoomIn" title="Zoom in">+</button>
  </div>
  <div class="group">
    <button id="exportSvg">Export SVG</button>
    <button id="exportPng">Export PNG</button>
    <button id="exportMmd">Export .mmd</button>
  </div>
</div>
<div id="diagram-wrap"><div id="diagram"><pre class="mermaid">
HTML_PART_B

echo "$diagram_body" >> "$HTML_FILE"

cat >> "$HTML_FILE" <<'HTML_PART_C'
</pre></div></div>
<script type="text/plain" id="erd-source">
HTML_PART_C

echo "$diagram_body" >> "$HTML_FILE"

cat >> "$HTML_FILE" <<'HTML_PART_D'
</script>
<script src="https://cdn.jsdelivr.net/npm/mermaid@10.9.1/dist/mermaid.min.js"></script>
<script>
  let scale = 1, baseW = 0, baseH = 0;

  function getSvg() { return document.querySelector('#diagram svg'); }

  function initSize() {
    const svg = getSvg();
    const vb = svg.viewBox && svg.viewBox.baseVal;
    if (vb && vb.width) { baseW = vb.width; baseH = vb.height; }
    else { const bb = svg.getBBox(); baseW = bb.width; baseH = bb.height; }
  }

  function applyZoom() {
    const svg = getSvg();
    svg.style.width = (baseW * scale) + 'px';
    svg.style.height = (baseH * scale) + 'px';
  }

  function downloadBlob(blob, filename) {
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url; a.download = filename;
    document.body.appendChild(a); a.click(); a.remove();
    URL.revokeObjectURL(url);
  }

  function serializedSvg() {
    const clone = getSvg().cloneNode(true);
    clone.setAttribute('xmlns', 'http://www.w3.org/2000/svg');
    clone.setAttribute('width', baseW);
    clone.setAttribute('height', baseH);
    return new XMLSerializer().serializeToString(clone);
  }

  window.addEventListener('DOMContentLoaded', async () => {
    mermaid.initialize({ startOnLoad: false, theme: 'default', securityLevel: 'loose' });
    await mermaid.run({ querySelector: '.mermaid' });
    initSize();

    document.getElementById('zoomIn').onclick = () => { scale = Math.min(scale * 1.2, 6); applyZoom(); };
    document.getElementById('zoomOut').onclick = () => { scale = Math.max(scale / 1.2, 0.15); applyZoom(); };
    document.getElementById('zoomReset').onclick = () => { scale = 1; applyZoom(); };

    document.getElementById('exportSvg').onclick = () => {
      downloadBlob(new Blob([serializedSvg()], { type: 'image/svg+xml' }), 'erd.svg');
    };

    document.getElementById('exportPng').onclick = () => {
      const url = URL.createObjectURL(new Blob([serializedSvg()], { type: 'image/svg+xml;charset=utf-8' }));
      const img = new Image();
      img.onload = () => {
        // Chrome caps canvas allocation around ~16k px per side / ~270M px total;
        // clamp the raster so large schemas still export instead of silently failing.
        const maxDim = 8000;
        const factor = Math.min(2, maxDim / baseW, maxDim / baseH);
        const canvas = document.createElement('canvas');
        canvas.width = Math.round(baseW * factor); canvas.height = Math.round(baseH * factor);
        const ctx = canvas.getContext('2d');
        ctx.fillStyle = '#ffffff';
        ctx.fillRect(0, 0, canvas.width, canvas.height);
        ctx.drawImage(img, 0, 0, canvas.width, canvas.height);
        URL.revokeObjectURL(url);
        canvas.toBlob((blob) => downloadBlob(blob, 'erd.png'));
      };
      img.src = url;
    };

    document.getElementById('exportMmd').onclick = () => {
      const src = document.getElementById('erd-source').textContent;
      downloadBlob(new Blob([src], { type: 'text/plain' }), 'erd.mmd');
    };
  });
</script>
</body>
</html>
HTML_PART_D

success "Wrote ${MD_FILE}"
success "Wrote ${HTML_FILE} (${table_count} tables, ${rel_count} relationships)"
