#!/usr/bin/env bash
# Generate TypeScript types from Go structs using tygo.
# Install once: go install github.com/gzuidhof/tygo@latest
#
# Usage: ./scripts/gen-types.sh
# Run from the repo root.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
BACKEND="$ROOT/backend"
OUT="$ROOT/frontend/types/generated"

if ! command -v tygo &>/dev/null; then
  echo "tygo not found — installing..."
  go install github.com/gzuidhof/tygo@latest
fi

mkdir -p "$OUT"

echo "Generating TypeScript types from Go structs..."
(cd "$BACKEND" && tygo generate)

# Prepend a header to each generated file so editors know it's auto-generated.
for f in "$OUT"/*.ts; do
  [ -f "$f" ] || continue
  tmp=$(mktemp)
  {
    echo "// Code generated by tygo — DO NOT EDIT."
    echo "// Source: backend/tygo.yaml"
    echo "// Run: ./scripts/gen-types.sh"
    echo ""
    cat "$f"
  } > "$tmp"
  mv "$tmp" "$f"
done

echo "Done. Types written to frontend/types/generated/"
