"""Non-history workspace files: IDE config, TICKET.md, INCIDENT.md, the
dev-environment setup script, data generators, stub services and env flags.

None of these are committed to the scenario's git history (they are listed in
.git/info/exclude), so `git status` and the student's diff stay clean.
"""
from __future__ import annotations

import json
import re
import shlex

from .errors import BuildError
from .inputs import Blocks
from .tree import Tree, read_block_file, safe_key

MANIFEST_NAME = "block.yaml"
DEV_DATABASE_URL = "postgresql://labuser@127.0.0.1:5432/app"
WORKDIR = "/home/labuser/work"
GENERATOR_RE = re.compile(r"^[A-Za-z0-9_./-]+$")
PROCESS_RE = re.compile(r"^[a-z][a-z0-9_-]*$")
PIP_PIN = "pip3 install --no-index --find-links /opt/wheels --user --break-system-packages -q "
DEBUGPY_PORT = 5678

INCIDENT_TEMPLATE = """# Incident write-up

<!-- Fill in each section. This is graded against what the platform knows about the real root cause. -->

## Symptom

What was reported, and what you observed.

## How I reproduced it

Exact steps, requests, or commands.

## Root cause

Why it happens (name the exact mechanism, not just where the code is).

## Fix

What you changed and why that removes the cause.

## Prevention

How to stop this class of bug from coming back (tests, checks, monitoring, design).
"""


def setup_commands(v: dict) -> list[str]:
    """Shell commands that build the app's runtime state, shared by the
    student's dev database (at session start) and every grader mode."""
    cmds: list[str] = []
    for env in v["envs"]:
        cmds += [PIP_PIN + shlex.quote(pin) for pin in env["pins"]]
    cmds += v["app"]["setup"]
    for d in v["data"]:
        gen = d["generator"]
        if not GENERATOR_RE.match(gen) or ".." in gen.split("/"):
            raise BuildError(f"data block {d['key']}: generator path {gen!r} is not a plain relative path")
        base = f"$MF_WORKDIR/.mf/data/{safe_key(d['key'])}"
        cmds.append(f'python3 "{base}/{gen}" "{base}/params.json"')
    return cmds


def _setup_sh(v: dict, cmds: list[str]) -> bytes:
    lines = [
        "#!/bin/bash",
        "# Generated by mf-build: prepares the development database and app state.",
        "# Run once by the platform at session start (as the lab user).",
        "set -euo pipefail",
        f"export MF_WORKDIR={WORKDIR}",
        f"export DATABASE_URL={shlex.quote(DEV_DATABASE_URL)}",
        f"export MF_SEED={v['seed_hex']}",
        'cd "$MF_WORKDIR"',
        *cmds,
        "mf-svc restart-workspace || true",
    ]
    return ("\n".join(lines) + "\n").encode()


def _vscode(v: dict) -> Tree:
    launch = {"version": "0.2.0", "configurations": [
        {"name": f"Attach to app (debugpy :{DEBUGPY_PORT})", "type": "debugpy", "request": "attach",
         "connect": {"host": "127.0.0.1", "port": DEBUGPY_PORT}, "justMyCode": False},
        {"name": "Debug current file", "type": "debugpy", "request": "launch", "program": "${file}",
         "console": "integratedTerminal"},
    ]}
    tasks = {"version": "2.0.0", "tasks": [
        {"label": "Run tests", "type": "shell", "command": "python3 -m pytest -q", "problemMatcher": []},
        {"label": "Restart app", "type": "shell", "command": "mf-svc restart-workspace", "problemMatcher": []},
        {"label": "App log", "type": "shell", "command": "tail -n 200 -f /var/log/mindforge-lab/app.log", "problemMatcher": []},
    ]}
    settings = {"python.defaultInterpreterPath": "/usr/bin/python3", "files.exclude": {".mf": True},
                "python.testing.pytestEnabled": True, "python.testing.unittestEnabled": False}
    dump = lambda o: (json.dumps(o, indent=2) + "\n").encode()  # noqa: E731
    return {".vscode/launch.json": dump(launch), ".vscode/tasks.json": dump(tasks), ".vscode/settings.json": dump(settings)}


def build_extras(v: dict, blocks: Blocks, cmds: list[str]) -> Tree:
    """Everything written into the workspace outside git history."""
    files: Tree = {}
    files.update(_vscode(v))
    files["TICKET.md"] = v["ticket_md"].encode()
    files["INCIDENT.md"] = INCIDENT_TEMPLATE.encode()
    files[".mf/setup.sh"] = _setup_sh(v, cmds)

    for d in v["data"]:
        root = f".mf/data/{safe_key(d['key'])}"
        for rel, data in blocks.get(d["dir"], {}).items():
            if rel != MANIFEST_NAME:
                files[f"{root}/{rel}"] = data
        read_block_file(blocks, d["dir"], d["generator"])  # must exist
        files[f"{root}/params.json"] = (json.dumps({"params": d["params"], "seed": v["seed_hex"], "variant": v["key"]},
                                                   indent=2, sort_keys=True) + "\n").encode()

    for s in v["stubs"]:
        if not PROCESS_RE.match(s["process"]):
            raise BuildError(f"stub {s['key']}: process name {s['process']!r} is invalid")
        root = f".mf/stubs/{safe_key(s['key'])}"
        for rel, data in blocks.get(s["dir"], {}).items():
            if rel != MANIFEST_NAME:
                files[f"{root}/{rel}"] = data
        files[f".lab/services/{s['process']}.sh"] = read_block_file(blocks, s["dir"], "service.sh")

    env_lines: list[str] = []
    for e in v["envs"]:
        for pair in e["supervisor"]:
            key, sep, val = pair.partition("=")
            if not sep or not re.match(r"^[A-Za-z_][A-Za-z0-9_]*$", key):
                raise BuildError(f"env {e['key']}: supervisor entry {pair!r} must be NAME=value")
            env_lines.append(f"export {key}={shlex.quote(val)}")
        if e["missing_var"]:
            if not re.match(r"^[A-Za-z_][A-Za-z0-9_]*$", e["missing_var"]):
                raise BuildError(f"env {e['key']}: missing_var {e['missing_var']!r} is not a variable name")
            env_lines.append(f"unset {e['missing_var']}")
    if env_lines:
        files[".lab/env"] = ("\n".join(env_lines) + "\n").encode()
    return files


def exclude_patterns(extras: Tree) -> list[str]:
    """.git/info/exclude entries for the generated, uncommitted files."""
    pats = ["/TICKET.md", "/INCIDENT.md", "/.vscode/", "/.mf/"]
    pats += sorted("/" + p for p in extras if p.startswith(".lab/"))
    return pats
